### ISSUE TITLE
Updating the rofi made the old configs inoperable

### ISSUE THREAD

**Issue by Pushkin31** [lr-tech/rofi-themes-collection#1]
Updating rofi to version `1.7.0` "killed" the old configs. Will your configs be updated to the current state?

p.s: they don't work now, tested :)

**Comment by ulises-jeremias** [comment]
It seems that this repo didn't have any update in the last 4 months. That is why I decided to fork it (preserving the LICENSE of course and copyright notes) and solve all the issue with latest rofi version. The new repo is here: https://github.com/ulises-jeremias/rofi-themes
I'll being updating the config today but I hope everything will be solved by the end of the week.
I'm not planning to create a new PR to this repo since I'm planning to add more themes too

**Comment by ulises-jeremias** [comment]
@Pushkin31 It seems that this repo didn't have any update in the last 4 months. That is why I decided to fork it (preserving the LICENSE of course and copyright notes) and solve all the issue with latest rofi version. The new repo is here: https://github.com/ulises-jeremias/rofi-themes
I'll being updating the config today but I hope everything will be solved by the end of the week.
I'm not planning to create a new PR to this repo since I'm planning to add more themes too

**Comment by newmanls** [comment]
I've been busy and haven't had time yet to update to the new rofi configs, but I'll be checking it out as soon as I can.
Also, @ulises-jeremias thank you for forking my repo!
