### ISSUE TITLE
No results shown when using splatmoji

### ISSUE THREAD

**Issue by PolGZ** [lr-tech/rofi-themes-collection#8]
Hi, newmanls. I love your themes. I've been using the rounded nord for a long time.

I'm also a long time [splatmoji](https://github.com/cspeterson/splatmoji) user, and I've been happily combining both of them on my main PC running Debian + bspwm.

I've been also running your rofi theme on my laptop on Arch + hyprland, but I've just realized that when using your themes no text/result/emoji is showed, regardless of the theme selected, but with the default rofi themes it works fine and everything is shown... 

So I don't know what to "blame".

Would you mind checking on that?

P.S.: I'll try to check on sway as well, but should be the same.

**Comment by newmanls** [comment]
Hello and thank you for using my themes!

I tried to reproduce your issue and it seems to work just fine for me, using both `splatmoji copy` and `splatmoji type` with several of my themes and found no issue. I also tried setting the rofi theme in the splatmoji config file with the same results:
```sh
# history_file=/home/myusername/.local/state/splatmoji/history
history_length=5
paste_command=xdotool key ctrl+v
rofi_command=rofi -dmenu -p '' -i -monitor -2 -theme "${HOME}/Repos/newmanls/rofi-themes-collection/themes/rounded-nord-dark.rasi"
xdotool_command=xdotool sleep 0.2 type --delay 100
xsel_command=xsel -b -i
```
You could check if both xdotool and xsel are working correctly. Since you are running wayland, maybe you should try replacing them with a wayland alternative, such as [ydotool](https://github.com/ReimuNotMoe/ydotool) and [wl-clipboard](https://github.com/bugaevc/wl-clipboard) or [clipman](https://github.com/yory8/clipman)
